insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '28-05-2024', 20854);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '16-05-2024', 30271);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '05-10-2024', 38472);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '01-03-2025', 68044);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '28-02-2025', 90369);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '28-10-2024', 5855);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '02-10-2024', 14457);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '01-06-2024', 94536);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '14-09-2024', 90380);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '12-10-2024', 41119);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '05-12-2024', 77907);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '20-01-2025', 36403);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '07-02-2025', 26145);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '15-09-2024', 44497);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '12-03-2025', 82299);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '11-02-2025', 81512);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '01-02-2025', 34238);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '10-01-2025', 87615);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '30-08-2024', 89383);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '25-06-2024', 74541);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '25-03-2025', 10169);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '14-05-2024', 40296);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '29-04-2025', 35752);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '27-06-2024', 63375);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '10-09-2024', 34892);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '15-02-2025', 2925);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '25-06-2024', 81944);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '07-06-2024', 12534);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '03-12-2024', 94101);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '06-02-2025', 13175);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '15-01-2025', 7371);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '24-08-2024', 4313);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '17-03-2025', 59159);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '24-03-2025', 3969);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '01-07-2024', 86680);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '19-05-2024', 84218);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '06-09-2024', 94775);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '27-09-2024', 490);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '09-06-2024', 38126);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '20-01-2025', 69162);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '22-07-2024', 47414);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '22-06-2024', 6407);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '11-11-2024', 28124);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '05-04-2025', 39208);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '22-09-2024', 24584);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '06-07-2024', 56261);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '13-12-2024', 63830);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '23-11-2024', 49125);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '15-09-2024', 65512);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '15-07-2024', 25081);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '11-12-2024', 22133);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '23-12-2024', 63492);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '30-12-2024', 77472);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '13-09-2024', 34022);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '06-06-2024', 33442);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '22-05-2024', 85424);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '23-05-2024', 80052);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '28-08-2024', 25014);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '07-09-2024', 55953);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '04-09-2024', 56043);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '25-10-2024', 92396);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '10-03-2025', 89948);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '17-12-2024', 46852);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '02-05-2024', 61642);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '17-10-2024', 54515);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '08-07-2024', 38404);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '21-03-2025', 19443);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '08-08-2024', 5397);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '03-01-2025', 78194);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '06-03-2025', 72693);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '03-02-2025', 753);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '16-12-2024', 63035);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '26-03-2025', 20441);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '08-04-2025', 73060);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '06-05-2024', 37984);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '25-12-2024', 75163);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '21-12-2024', 55839);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '08-01-2025', 16855);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '20-04-2025', 96295);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '24-02-2025', 68730);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '29-11-2024', 3301);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '26-02-2025', 74720);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '14-02-2025', 50953);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '12-06-2024', 12664);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '29-10-2024', 15311);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '22-11-2024', 88664);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '10-08-2024', 37756);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '10-11-2024', 94785);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '05-07-2024', 48065);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '02-07-2024', 10417);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '24-02-2025', 59992);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/ff4444/ffffff', '15-06-2024', 75464);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '15-11-2024', 81223);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '25-03-2025', 28194);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '07-05-2024', 78596);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/cc0000/ffffff', '28-03-2025', 31932);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '19-06-2024', 22620);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '31-07-2024', 34882);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/5fa2dd/ffffff', '25-12-2024', 85519);
insert into products (name, description, image, production_date, cost) values ('Example', '
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum libero exercitationem voluptas rerum odit in id minus vero autem? Facere tenetur quidem totam illo. Voluptatem quia suscipit accusantium sapiente quo pariatur harum a doloribus, odio dicta delectus laboriosam commodi ad aut, excepturi voluptatum quis? Ut reprehenderit placeat repellendus possimus architecto.', 'http://dummyimage.com/x.png/dddddd/000000', '11-02-2025', 600);
